// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenWealth.Api.Data;

#nullable disable

namespace OpenWealth.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714120116_AddLedgerEntries")]
    partial class AddLedgerEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("OpenWealth.Api.Models.AccrualEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NewBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("AccrualEvents");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.CustomAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedAnnualGrowthPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CustomAssets");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.CustomDebt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AnnualInterestRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MonthlyPayment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReinvestDestinationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReinvestDestinationType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ReinvestMonthlyAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CustomDebts");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.IncomeDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualBonus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutomationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildrenReceivingChildBenefit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EmployeePensionPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerPensionPercent")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastAccrualDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaydayDayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PensionMethod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PensionOnBonus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("IncomeDetails");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.Investment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedAnnualGrowthPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReceivesIncomePensionContributions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.Mortgage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualInterestRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FixedRateEndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FollowOnRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutstandingBalance")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RateType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReinvestDestinationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReinvestDestinationType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ReinvestMonthlyAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("TermMonthsRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Mortgages");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.NetWorthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Investments")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mortgages")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetWorth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtherAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtherDebts")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Property")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Savings")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StudentLoans")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalLiabilities")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("NetWorthSnapshots");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.SavingsAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AnnualInterestRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyDeposit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavingsAccounts");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.ShareSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassphraseHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ShareSettings");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.StudentLoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Plan")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StudentLoans");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.StudentLoanPlanSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualRepaymentThreshold")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("Plan")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RepaymentRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Plan")
                        .IsUnique();

                    b.ToTable("StudentLoanPlanSettings");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.TaxSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdditionalRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicRateLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChildBenefitAdditionalChildWeekly")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChildBenefitFirstChildWeekly")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChildcareIncomeLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HicbcLowerThreshold")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HicbcUpperThreshold")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HigherRateLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HigherRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NiMainRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NiPrimaryThresholdAnnual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NiUpperEarningsLimitAnnual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NiUpperRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PersonalAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PersonalAllowanceTaperThreshold")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxYearLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TaxSettings");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.AccrualEvent", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.CustomAsset", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithMany("CustomAssets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.CustomDebt", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithMany("CustomDebts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.IncomeDetails", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithOne("Income")
                        .HasForeignKey("OpenWealth.Api.Models.IncomeDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.Investment", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithMany("Investments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.LedgerEntry", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.Mortgage", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.Property", null)
                        .WithMany("Mortgages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithMany("Mortgages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.NetWorthSnapshot", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.Property", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithMany("Properties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.SavingsAccount", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithMany("SavingsAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.ShareSettings", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithOne("ShareSettings")
                        .HasForeignKey("OpenWealth.Api.Models.ShareSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.StudentLoan", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithMany("StudentLoans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.StudentLoanPlanSetting", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithMany("StudentLoanPlanSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.TaxSettings", b =>
                {
                    b.HasOne("OpenWealth.Api.Models.User", null)
                        .WithOne("TaxSettings")
                        .HasForeignKey("OpenWealth.Api.Models.TaxSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenWealth.Api.Models.Property", b =>
                {
                    b.Navigation("Mortgages");
                });

            modelBuilder.Entity("OpenWealth.Api.Models.User", b =>
                {
                    b.Navigation("CustomAssets");

                    b.Navigation("CustomDebts");

                    b.Navigation("Income");

                    b.Navigation("Investments");

                    b.Navigation("Mortgages");

                    b.Navigation("Properties");

                    b.Navigation("SavingsAccounts");

                    b.Navigation("ShareSettings");

                    b.Navigation("StudentLoanPlanSettings");

                    b.Navigation("StudentLoans");

                    b.Navigation("TaxSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
